### ISSUE TITLE
Missing ~/.pwrc?

### ISSUE THREAD

**Issue by gr4kk3r** [clieg/pwy#10]
I've used pwy for a while to make a quick check on a sibling living in Japan. I tried it yesterday and got the following

```
Traceback (most recent call last):
  File "/home/user/.local/bin/pwy", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.9/site-packages/pwy/cli.py", line 202, in main
    info = get_weather_data(location, unit, lang)
  File "/home/user/.local/lib/python3.9/site-packages/pwy/cli.py", line 35, in get_weather_data
    f"&appid={get_key()}&units={unit}&lang={lang}")
  File "/home/user/.local/lib/python3.9/site-packages/pwy/cli.py", line 20, in get_key
    with open(f"{home}/.pwyrc") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.pwyrc'
```
Obviously missing a .pwyrc, but what should I put there? I don't see it on the github page. I tried uninstalling and reinstalling both via pip3 and cloning the repo. Same issue. Any help appreciated.

**Comment by egargo** [comment]
Thank you for the issue.

Did you set your OWM API key? If not, you need to run the command `pwy --config <YOUR_OWM_API_KEY>`, after that you should be good to go. (;
*Note: You need to wait for your OWM API key to be activated, it's an OWM thing.*

If the issue still persists, please let me know.

**Comment by gr4kk3r** [comment]
Well, damn. That was probably on me. I've been moving a ton of stuff around trying to...well, it doesn't really matter.

All good now. Thanks.

**Comment by egargo** [comment]
Thank you! (;
