### ISSUE TITLE
name 'light_rain' is not defined

### ISSUE THREAD

**Issue by jarun** [clieg/pwy#2]
getting the following error:

```
$ wwy -c kolkata  
Traceback (most recent call last):
  File "/usr/local/bin/wwy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/wwy/__main__.py", line 92, in main
    get_ascii(info)
  File "/usr/local/lib/python3.8/dist-packages/wwy/__main__.py", line 69, in get_ascii
    for i in range(len(light_rain)):
NameError: name 'light_rain' is not defined
```

Please fix.

**Comment by jarun** [comment]
Also can you please make the place name the default positional parameter? So that `-c` is not required?

**Comment by egargo** [comment]
Thank you for reporting the error. I have now fixed the error. I will also be working on making the place name as the default parameter.

**Comment by jarun** [comment]
Awesome! Neat software. All the best!

**Comment by jarun** [comment]
Would it be possible to include wind speed and the local time as well?

**Comment by egargo** [comment]
I will try to implement that. I also wanted wwy to display the local time.
