### ISSUE TITLE
Error when fetching weather

### ISSUE THREAD

**Issue by jarun** [clieg/pwy#5]
With the latest available on pip:

```
$ wwy kolkata
Traceback (most recent call last):
  File "/usr/local/bin/wwy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/wwy/__main__.py", line 146, in main
    display_weather_info(info)
  File "/usr/local/lib/python3.8/dist-packages/wwy/__main__.py", line 118, in display_weather_info
    for line in ascii:
TypeError: 'NoneType' object is not iterable
```

**Comment by egargo** [comment]
I apologise fro the inconvenience. What package name are you using? I recently moved the project from wwy to [pwy](https://pypi.org/project/pwy/). You can uninstall the old package and install the new one :)

**Comment by jarun** [comment]
Thanks. GitHub still redirects to this page.

**Comment by jarun** [comment]
`pwy` works fine. Any plans to show the local time at the place?

**Comment by egargo** [comment]
I've added the local time, but I haven't updated the PyPi package yet. I want to get it tested first.
Here's a snippet of it:
```
	            Cagayan de Oro, PH
	  .-.       Temperature: 23.28°C (24.14°C)
	 (   ).-.   Clouds. Overcast Clouds
	(________)  Pressure: 1012hPa  Humidity: 95%  Wind: 1.2km/h
	            Time: 21:06 PST
```

**Comment by jarun** [comment]
Can't wait for it to be available in PyPi!

**Comment by egargo** [comment]
I've updated the PyPi package. Feel free to create an issue if you found any problems wit it.

**Comment by jarun** [comment]
This shows the local time. I was suggesting adding the time at the location looked up.

**Comment by egargo** [comment]
I've fixed the local time. It now shows the time of the location that is being looked up. You can update the package now.
