### ISSUE TITLE
Publish release assets for package building

### ISSUE THREAD

**Issue by CultofRobots** [clieg/pwy#8]
If you could, I would appreciate it if you could upload zip and/or tar.gz files as releases so this can be built with python-setuptools and installed with a package manager. Please also include the api key in key.py in the compressed assets or add a switch so we can use our own openweathher api keys. Thanks.

**Comment by egargo** [comment]
Thanks for the issue. I will add a tar.gz on the next release. I will also work on switch so others an add their own API keys.

**Comment by egargo** [comment]
I have added a zip and tar.gz archive for the new update. As of for the API key, one will have to add theirs in pwy/key.py file.
