### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by farzadmf** [clieg/pwy#9]
Hi, I've created my API key and I've done `pwy --config <api-key>`, but when I do, say, `pwy montreal`, I see the following error:

```
Invalid API key.
Traceback (most recent call last):
  File "/data/dev/pytools/pwy/bin/pwy", line 8, in <module>
    sys.exit(main())
  File "/data/dev/pytools/pwy/lib/python3.9/site-packages/pwy/cli.py", line 202, in main
    info = get_weather_data(location, unit, lang)
  File "/data/dev/pytools/pwy/lib/python3.9/site-packages/pwy/cli.py", line 52, in get_weather_data
    "name": data["name"],
KeyError: 'name'
```

**Comment by egargo** [comment]
Thank you for the issue. Did you just generated an API key? If yes, please wait a couple of minutes for your API key to activate, and retry the command. If the issue still persists, please let me know.

**Comment by farzadmf** [comment]
Oh nice to know. It works now. Not sure if I missed it, but maybe it's worth mentioning this (that you need to wait) in the README (if not already there)

I'm going to close the issue since it's resolved for me :slightly_smiling_face:

**Comment by egargo** [comment]
Glad that it worked! (;
Yes, I should mention it on the README.
